name: NASA API Call

on:
  workflow_dispatch:

jobs:
  nassa-api-call:
    runs-on: ubuntu-latest

    steps:
      - name: Create out folder
        run: mkdir -p out
    
      - name: Call API
        run: curl https://api.nasa.gov/planetary/apod?api_key=${{ secrets.NASA_SECRET }} -o out/output.json

      - name: Get image 
        run: hdurl=$(jq -r '.hdurl' out/output.json) && curl $hdurl -o out/nasa.jpg

      - name: Upload out folder
        uses: actions/upload-artifact@v4
        with:
          name: json-and-img
          path: out/**
