name: NASA API Call

on:
  workflow_dispatch:

jobs:
  nassa-api-call:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo "echo"
    
      - name: Call API
        run: curl https://api.nasa.gov/planetary/apod?api_key=${{ secrets.DEMO_KEY }} -o out/output.json

      - name: get image 
        run: hdurl=$(jq -r '.hdurl' output.json) && curl $hdurl -o out/nasa.jpg

      - name: Upload output.json
        uses: actions/upload-artifact@v4
        with:
          name: output-json
          path: out/**

      # - name: Upload output.json
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: output-jpg
      #     path: nasa.jpg
      
