name: NASA API Call - PY

on:
  workflow_dispatch:

jobs:
  nassa-api-call:
    runs-on: ubuntu-latest

    steps:
      - name: run py
        run: python -V

      - name: make output dir
        run: mkdir -p out

      - name: run py
        run: python ./get-nasa-image.py
        env:
          NASA_SECRET: ${{ secrets.NASA_SECRET }}

      - name: Upload output.json
        uses: actions/upload-artifact@v4
        with:
          name: json-and-img
          path: out/**
